baseurl = "https://stp5.net/"
languageCode = "en-us"
title = "stp5.net"
# Define how many pages appear per site
paginate = 10
theme = "minimalist"
# syntax highlighing
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[permalinks]
    blog = "/blog/post/:title/"

[params]
    site_author = "Stephen Price"
    site_description = "stp5.net"
    location = "Portland, OR"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "images/profile-image.png"
    header_background = "images/bg.jpg"
    header_title = "stp‚Åµ"
    copyright = "<a href=\"https://github.com/steeef\">Stephen Price</a>"

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "steeef"
    facebook  = ""
    linkedin  = ""
    instagram = ""
    github    = "steeef"
    gplus     = "steeef"
